#!/usr/bin/env python3
from __future__ import annotations

import hashlib
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SPEC_PATH = ROOT / "contractkit" / "spec" / "contractkit_spec_v1.json"

PY_OUT = ROOT / "poker2" / "contractkit" / "_generated.py"


def _stable_json_bytes(obj: object) -> bytes:
    return json.dumps(obj, ensure_ascii=False, sort_keys=True, separators=(",", ":")).encode("utf-8")


def _sha256_hex(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def _read_spec() -> tuple[dict, str]:
    spec = json.loads(SPEC_PATH.read_text(encoding="utf-8"))
    spec_digest = _sha256_hex(_stable_json_bytes(spec))
    return spec, spec_digest


def _write(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8", newline="\n") as f:
        f.write(content)


def _gen_python(spec: dict, spec_digest: str) -> str:
    rounding_modes = spec["controlled_enums"]["rounding_mode"]
    rounding_modes_py = ", ".join([repr(x) for x in rounding_modes])
    return f'''# GENERATED by contractkit/generate.py from {SPEC_PATH.as_posix()}
# spec_digest_sha256={spec_digest}
# DO NOT EDIT.

from __future__ import annotations

import hashlib
import re
from dataclasses import dataclass
from typing import Any


ROUNDING_MODE_VALUES = ({rounding_modes_py},)

_SHA256_HEX_RE = re.compile(r"^[0-9a-f]{{64}}$")


@dataclass
class ContractKitError(Exception):
    code: str
    message: str

    def __str__(self) -> str:  # pragma: no cover
        return f"{{self.code}}: {{self.message}}"


def sha256_hex(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def _is_seatmap_field_name(field_name: str | None) -> bool:
    if not field_name:
        return False
    return ("_by_seat" in field_name) or field_name.startswith("by_seat_")


def _validate_seat_key(key: str, strict_mode: bool) -> int:
    if key == "0":
        return 0
    if not key.isdigit():
        raise ContractKitError("SEAT_KEY_NOT_DECIMAL", f"seat key must be decimal string, got={{key!r}}")
    if key.startswith("0"):
        if strict_mode:
            raise ContractKitError("SEAT_KEY_LEADING_ZERO", f"seat key must not have leading zeros, got={{key!r}}")
    return int(key)


def _escape_json_string(value: str) -> str:
    out: list[str] = ['"']
    for ch in value:
        code = ord(ch)
        if ch == '"':
            out.append(r'\\"')
        elif ch == "\\\\":
            out.append(r"\\\\")
        elif ch == "\\b":
            out.append(r"\\b")
        elif ch == "\\f":
            out.append(r"\\f")
        elif ch == "\\n":
            out.append(r"\\n")
        elif ch == "\\r":
            out.append(r"\\r")
        elif ch == "\\t":
            out.append(r"\\t")
        elif code < 0x20:
            out.append(f"\\\\u{{code:04x}}")
        else:
            out.append(ch)
    out.append('"')
    return "".join(out)


def _canonicalize(value: Any, *, strict_mode: bool, parent_key: str | None) -> str:
    if value is None:
        return "null"
    if value is True:
        return "true"
    if value is False:
        return "false"
    if isinstance(value, int):
        return str(value)
    if isinstance(value, float):
        raise ContractKitError("FLOAT_NOT_ALLOWED", "float is not allowed in canonical hash input")
    if isinstance(value, str):
        return _escape_json_string(value)
    if isinstance(value, list):
        inner = ",".join(_canonicalize(v, strict_mode=strict_mode, parent_key=None) for v in value)
        return f"[{{inner}}]"
    if isinstance(value, dict):
        is_seatmap = _is_seatmap_field_name(parent_key)
        if is_seatmap and strict_mode and len(value) == 0:
            raise ContractKitError("SEATMAP_EMPTY", "seatmap must not be empty object in strict_mode (use null/missing)")

        items: list[tuple[str, Any]] = []
        for k, v in value.items():
            if not isinstance(k, str):
                raise ContractKitError("OBJECT_KEY_NOT_STRING", f"object key must be string, got={{type(k).__name__}}")
            items.append((k, v))

        if is_seatmap:
            items.sort(key=lambda kv: _validate_seat_key(kv[0], strict_mode))
        else:
            items.sort(key=lambda kv: kv[0])

        out = ["{{"]
        first = True
        for k, v in items:
            if not first:
                out.append(",")
            first = False
            out.append(_escape_json_string(k))
            out.append(":")
            out.append(_canonicalize(v, strict_mode=strict_mode, parent_key=k))
        out.append("}}")
        return "".join(out)

    raise ContractKitError("UNSUPPORTED_TYPE", f"unsupported JSON type: {{type(value).__name__}}")


def canonicalize_json_bytes(value: Any, *, strict_mode: bool = True) -> bytes:
    return _canonicalize(value, strict_mode=strict_mode, parent_key=None).encode("utf-8")


def validate_digest_object(value: Any, *, strict_mode: bool = True) -> None:
    if not isinstance(value, dict):
        raise ContractKitError("DIGEST_NOT_OBJECT", "digest must be an object")
    alg = value.get("alg")
    hex_str = value.get("hex")

    if alg != "sha256":
        raise ContractKitError("DIGEST_ALG_NOT_ALLOWED", "digest.alg must be 'sha256'")
    if not isinstance(hex_str, str):
        raise ContractKitError("DIGEST_HEX_NOT_STRING", "digest.hex must be a string")
    if len(hex_str) != 64:
        raise ContractKitError("DIGEST_HEX_WRONG_LEN", "digest.hex must be 64 chars for sha256")
    if hex_str.lower() != hex_str:
        raise ContractKitError("DIGEST_HEX_NOT_LOWER", "digest.hex must be lowercase")
    if not _SHA256_HEX_RE.fullmatch(hex_str):
        raise ContractKitError("DIGEST_HEX_NOT_HEX", "digest.hex must be lowercase hex")

    if strict_mode:
        extra = set(value.keys()) - {{"alg", "hex"}}
        if extra:
            raise ContractKitError("DIGEST_EXTRA_FIELDS", f"digest has extra fields: {{sorted(extra)!r}}")
'''


def main() -> int:
    spec, spec_digest = _read_spec()

    _write(PY_OUT, _gen_python(spec, spec_digest))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
